apiVersion: skaffold/v1beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: cabhiram/multik8s-app
      context: app
      docker:
        dockerfile: Dockerfile
      sync:
        '**/*.py': .
        '**/*.css': .
        '**/*.html': .
    - image: cabhiram/web-api
      context: web-api
      docker:
        dockerfile: Dockerfile
      sync:
        '**/*.py': .
deploy:
  kubectl:
    manifests:
      - k8s/app-deployment.yaml
      - k8s/api-deployment.yaml
