apiVersion: v1
kind: Service
metadata:
  name: app-cluster-ip-service
spec:
  type: NodePort
  selector:
    component: clientapp
  ports:
    - port: 7050
      targetPort: 7000
      nodePort: 31515
