apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: clientapp
  template:
    metadata:
      labels:
        component: clientapp
    spec:
      containers:
        - name: clientapp
          image: cabhiram/multik8s-app
          ports:
            - containerPort: 7000
